### ISSUE TITLE
I'm new with Node. I have errors when run "npm start". Can anyone help me?

### ISSUE THREAD

**Issue by davizote** [fnakstad/angular-client-side-auth#65]
users-Mac:angular-client-side-auth-master user$ npm start

> angular-client-side-auth@0.0.1 start /Users/user/Documents/Proyects/angular-client-side-auth-master
> grunt dev

sh: grunt: command not found

npm ERR! angular-client-side-auth@0.0.1 start: `grunt dev`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the angular-client-side-auth@0.0.1 start script.
npm ERR! This is most likely a problem with the angular-client-side-auth package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-client-side-auth
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/user/Documents/Proyects/angular-client-side-auth-master
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/user/Documents/Proyects/angular-client-side-auth-master/npm-debug.log
npm ERR! not ok code 0
users-Mac:angular-client-side-auth-master user$

**Comment by jshemas** [comment]
Do you have Grunt's command line interface installed globally?

If not, the command is:
`npm install -g grunt-cli`

Then try:
`npm install`
Then:
`npm start`

**Comment by fnakstad** [comment]
It sounds like @jshemas' suggestion is the right one! Could you confirm, @davizote?
Also, note that I just pushed a commit where I include the grunt-cli as a dev dependency. This will enable the use of the locally installed grunt-cli when no global install has been made.

**Comment by davizote** [comment]
Sorry for the delay. It works correctly now.
Thanks for all.

I will try to implement this proyect with mongoose data persistence and bcrypt encryption password.

Hope everything goes well because I'm very noob with node.

**Comment by DarkManiel** [comment]
Hi guys, I'm having a similar problem on Windows 7. 

I installed the grunt command line interface from what you mentioned above. Should I then do npm install in git bash or the grunt command line interface? If I try to open grunt command line interface, it opens then immediately closes. If I run npm install in git bash it says >angular-phonecat@0.0.0 postinstall c:\phonecat\angular-phonecat > bower install. When I run npm start it says >angular-phonecat@0.0.0 startc:\phonecat\angular-phonecat >  http-server -p 8000. 

Then if I try to run     http://localhost:8000/app/index.html in chrome, it doesn't load. Also, I can't seem to find the bower_components directory that is mentioned on the angularjs site. 

Any help would be appreciated.

**Comment by fnakstad** [comment]
Do you also have bower installed globally? `npm install` will call `bower install` as a post-install hook. So, if bower is not installed globally, this step will fail and no bower_components directory be created. Try running `npm install -g bower`, and then running `npm install` again.

**Comment by DarkManiel** [comment]
Thanks for your reply. I followed your instructions, but still no luck. The global install of bower seemed to work fine. At the end I got the following result and then ran npm install as such:

2.10, request@2.27.0, bower-config@0.4.5)

Mark@MARK-PC /C/PhoneCat/angular-phonecat (master)
$ npm install

> angular-phonecat@0.0.0 postinstall c:\PhoneCat\angular-phonecat
> bower install

Mark@MARK-PC /C/PhoneCat/angular-phonecat (master)
$ npm start

> angular-phonecat@0.0.0 start c:\PhoneCat\angular-phonecat
> http-server -p 8000

Mark@MARK-PC /C/PhoneCat/angular-phonecat (master)
$

One curious thing is that if I run npm install -g karma I get the following:

> ws@0.4.31 install C:\Users\Mark\AppData\Roaming\npm\node_modules\karma\node_mo
> dules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

and if I try to do it for ws, I get: 
C:\Users\Mark\AppData\Roaming\npm\wscat -> C:\Users\Mark\AppData\Roaming\npm\nod
e_modules\ws\bin\wscat

> ws@0.4.31 install C:\Users\Mark\AppData\Roaming\npm\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

I don't know if I need to install these items or not, but it seems strange that they aren't building properly. Do you think this might be part of the problem? Thanks a bunch for your help.

-Mark

**Comment by fnakstad** [comment]
Hi Mark,
This is quite strange. Karma should not have anything to do with your problem as far as I know. `npm install` does not report any errors? What exactly is the error message you receive when running `npm start`?

PS! When you see `(node-gyp rebuild 2> builderror.log) || (exit 0)` displayed, just let it work for a while. Don't cancel it prematurely thinking it's hanging or anything. node-gyp simply takes a while to finish.

**Comment by DarkManiel** [comment]
Thanks fnakstad,
I finally figured it out. I downloaded visual c++ and that seemed to do the trick. I'm not 100% sure it that's what did it, but regardless, I'm in business now. Thanks so much for your help! I'm loving Angularjs so far.

Mark

**Comment by fnakstad** [comment]
Visual C++ did the trick? Hmmm, I can't think of any reason why. Anyway, happy things are working for you now :)

**Comment by skdurgesh** [comment]
Well guys sorry for silly question here, when i am going to code in angularJs, Why do i need to install all this package like- Git, npm, bower, karma, protractor etc. i think i have installed everything here, but still i have this error when try to start "npm start". and also i am attaching this log file. i am not getting where the problems coming from.?

![npmlog_file](https://cloud.githubusercontent.com/assets/7554475/2984744/a4e93b80-dc35-11e3-8fb6-1d9131430c41.png)

**Comment by jshemas** [comment]
High level overview:
Git - Code Version Control. - http://git-scm.com/
npm -  For installing Node.js  packages like express.js or passport.js - https://www.npmjs.org/
bower - For installing web libraries like jquery or angular  - http://bower.io/
karma and protractor - Used for testing - http://karma-runner.github.io/0.12/index.html - https://github.com/angular/protractor

Looking at your error log, are you trying to run Angular's "PhoneCat Tutorial App?" -https://docs.angularjs.org/tutorial

**Comment by fnakstad** [comment]
@skdurgesh Are you sure you posted this issue in the right repo? Perhaps try the angular-phonecat repo instead?

Anyway, jshemas provided a good description of the various components.

**Comment by skdurgesh** [comment]
First of all Thanks @fnakstad, @jshemas, 
yes @jshemas it's angular-phonecat tutorial, but what about my project have to check in local server..? how i am going to do that.? please guide me on this
@fnakstad i am not sure about this at all , as i am rookie in the angularJS so i don't know what i am doing.

**Comment by fnakstad** [comment]
I think posting your issue at the [angular/angular-phonecat](https://github.com/angular/angular-phonecat) repo will gain you more answers if that's the repo you're having trouble with.

Reading the error trace it says that the error occurs when running the `npm prestart` command. If you check the `package.json` file of angular-phonecat it says that [this command](https://github.com/angular/angular-phonecat/blob/master/package.json#L18) simply fires `npm install`. So try running `npm install` in the project directory and see if that returns any errors. Maybe you have a faulty installation of npm...?

**Comment by skdurgesh** [comment]
thanks @fnakstad,i will definitely give it a try.. :) i hope it will work..

**Comment by rgurgul** [comment]
I have the same problem with angular-phonecat in window 8. 
I managed run protractor by: protractor test/protractor-conf.js
I hope it help

**Comment by alexmiller00** [comment]
I'm getting warnings on npm install and errors on npm start, i'm trying to run a parse server, i followed a few of the tips mentioned above but thy seemed to add more errors, im guesing there is a configuration problem somewhere but i dont even know where to start? any help would be great! thanks!
root@lawondemand:~# npm install
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
root@lawondemand:~# npm start
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by ghost** [comment]
Hey Guys I have the similar problem in ubuntu:
$ npm start

> x-component-healthstatus@0.1.0 start /home/x/x/ecc-component-healthstatus
> gulp

sh: 1: gulp: not found

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/x/.nvm/versions/node/v6.0.0/bin/node" "/home/x/.nvm/versions/node/v6.0.0/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ecc-component-healthstatus@0.1.0 start: `gulp`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ecc-component-healthstatus@0.1.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ecc-component-healthstatus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ecc-component-healthstatus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ecc-component-healthstatus
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/x/x/x-component-healthstatus/npm-debug.log

**Comment by anu6767** [comment]
Hi,
I am also new to React JS.
I am getting below error while npm start :+1: 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle regenerator-transform@0.9.8~prestart: regenerator-transform@0.9.8
7 silly lifecycle regenerator-transform@0.9.8~prestart: no script for prestart, continuing
8 info lifecycle regenerator-transform@0.9.8~start: regenerator-transform@0.9.8
9 verbose lifecycle regenerator-transform@0.9.8~start: unsafe-perm in lifecycle true
10 verbose lifecycle regenerator-transform@0.9.8~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Application Virtualization Client;C:\Program 

13 silly lifecycle regenerator-transform@0.9.8~start: Returned: code: 4294967295  signal: null
14 info lifecycle regenerator-transform@0.9.8~start: Failed to exec start script
15 verbose stack Error: regenerator-transform@0.9.8 start: `webpack-dev-server --hot --inline`
15 verbose stack Exit status 4294967295
15 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at EventEmitter.emit (events.js:191:7)
15 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at ChildProcess.emit (events.js:191:7)
15 verbose stack     at maybeClose (internal/child_process.js:886:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
16 verbose pkgid regenerator-transform@0.9.8
18 error Windows_NT 6.1.7601
19 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
20 error node v6.10.1
21 error npm  v3.10.10
22 error code ELIFECYCLE
23 error regenerator-transform@0.9.8 start: `webpack-dev-server --hot --inline`
23 error Exit status 4294967295
24 error Failed at the regenerator-transform@0.9.8 start script 'webpack-dev-server --hot --inline'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the regenerator-transform package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack-dev-server --hot --inline
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs regenerator-transform
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls regenerator-transform
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]


Please help me out

**Comment by hajarrhechchou** [comment]
Hey Guys I have a problem
Please help me :(


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hajar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle design-angular2@1.2.0~prestart: design-angular2@1.2.0
6 info lifecycle design-angular2@1.2.0~start: design-angular2@1.2.0
7 verbose lifecycle design-angular2@1.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle design-angular2@1.2.0~start: PATH: C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules\.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\sts-bundle\sts-3.8.4.RELEASE;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\hajar\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Users\hajar\Desktop\vsc\veille\app2
9 verbose lifecycle design-angular2@1.2.0~start: CWD: C:\Users\hajar\Desktop\vsc\veille\app2
10 silly lifecycle design-angular2@1.2.0~start: Args: [ '/d /s /c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
11 silly lifecycle design-angular2@1.2.0~start: Returned: code: 2  signal: null
12 info lifecycle design-angular2@1.2.0~start: Failed to exec start script
13 verbose stack Error: design-angular2@1.2.0 start: `tsc && concurrently "tsc -w" "lite-server" `
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid design-angular2@1.2.0
15 verbose cwd C:\Users\hajar\Desktop\vsc\veille\app2
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hajar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error design-angular2@1.2.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the design-angular2@1.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by hajora123** [comment]
Hey Guys 
Please help me :(

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hajar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle design-angular2@1.2.0~prestart: design-angular2@1.2.0
6 info lifecycle design-angular2@1.2.0~start: design-angular2@1.2.0
7 verbose lifecycle design-angular2@1.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle design-angular2@1.2.0~start: PATH: C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules\.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\sts-bundle\sts-3.8.4.RELEASE;C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.4;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\hajar\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Users\hajar\Desktop\vsc\veille\app2\node_modules
9 verbose lifecycle design-angular2@1.2.0~start: CWD: C:\Users\hajar\Desktop\vsc\veille\app2
10 silly lifecycle design-angular2@1.2.0~start: Args: [ '/d /s /c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
11 silly lifecycle design-angular2@1.2.0~start: Returned: code: 2  signal: null
12 info lifecycle design-angular2@1.2.0~start: Failed to exec start script
13 verbose stack Error: design-angular2@1.2.0 start: `tsc && concurrently "tsc -w" "lite-server" `
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\hajar\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid design-angular2@1.2.0
15 verbose cwd C:\Users\hajar\Desktop\vsc\veille\app2
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hajar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error design-angular2@1.2.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the design-angular2@1.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by beingbing** [comment]
i too have a similar problem

when i run  $npm run copyfonts

> confusion@1.0.0 copyfonts /home/samar/Desktop/coursera-practice/Bootstrap4/conFusion
> copyfiles -f node_modules/font-awesome/fonts/* dist/fonts

sh: 1: copyfiles: not found

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "copyfonts"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! confusion@1.0.0 copyfonts: `copyfiles -f node_modules/font-awesome/fonts/* dist/fonts`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the confusion@1.0.0 copyfonts script 'copyfiles -f node_modules/font-awesome/fonts/* dist/fonts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the confusion package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     copyfiles -f node_modules/font-awesome/fonts/* dist/fonts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs confusion
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls confusion
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/samar/Desktop/coursera-practice/Bootstrap4/conFusion/npm-debug.log

**Comment by jshemas** [comment]
Guys, this issue was closed in 2014. Please open a new issue if you have any problems.

**Comment by jabbar86** [comment]
I am getting this error while starting the npm 
$ npm start

> angular@1.0.0 start C:\Users\Jabbar Memon\Downloads\Angular-2-Tutorials-master\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/@angular/core/index.d.ts(26,1): error TS1128: Declaration or statement expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jabbar Memon\AppData\Roaming\npm-cache\_logs\2017-09-15T06_58_41_281Z-debug.log

**Comment by erangasandaruwan** [comment]
I am having the same issues with "npm start".

> local.rateengine@1.0.0 start C:\Users\Dev1\Desktop\Node js\Application\local.RateEngine
> node ./rest/server.js

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './rest/controllers/carrierController'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Dev1\Desktop\Node js\Application\local.RateEngine\rest\server.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! local.rateengine@1.0.0 start: `node ./rest/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the local.rateengine@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev1\AppData\Roaming\npm-cache\_logs\2018-05-27T14_07_26_091Z-debug.log

and this is my log
----------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Dev1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle local.rateengine@1.0.0~prestart: local.rateengine@1.0.0
6 info lifecycle local.rateengine@1.0.0~start: local.rateengine@1.0.0
7 verbose lifecycle local.rateengine@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle local.rateengine@1.0.0~start: PATH: C:\Users\Dev1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Dev1\Desktop\Node js\Application\local.RateEngine\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\OpenVPN\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\Dev1\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\Dev1\AppData\Roaming\npm
9 verbose lifecycle local.rateengine@1.0.0~start: CWD: C:\Users\Dev1\Desktop\Node js\Application\local.RateEngine
10 silly lifecycle local.rateengine@1.0.0~start: Args: [ '/d /s /c', 'node ./rest/server.js' ]
11 silly lifecycle local.rateengine@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle local.rateengine@1.0.0~start: Failed to exec start script
13 verbose stack Error: local.rateengine@1.0.0 start: `node ./rest/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Dev1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Dev1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid local.rateengine@1.0.0
15 verbose cwd C:\Users\Dev1\Desktop\Node js\Application\local.RateEngine
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dev1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.2.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error local.rateengine@1.0.0 start: `node ./rest/server.js`
22 error Exit status 1
23 error Failed at the local.rateengine@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Anybody plz help me out

**Comment by jaswanth2001** [comment]
I am getting like this can anyone help

C:\Windows\system32>npm start
npm ERR! path C:\Windows\system32\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Windows\system32\pac
kage.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\welcome\AppData\Roaming\npm-cache\_logs\2018-12-09T11_47_5
9_658Z-debug.log
![capture](https://user-images.githubusercontent.com/45732558/49696919-0a0d8a00-fbd7-11e8-9f39-bb0698348e23.PNG)

**Comment by bhautikkeraliya** [comment]
This solution worked for me:
https://github.com/fnakstad/angular-client-side-:auth/issues/65#issuecomment-35918039

**Comment by ghost** [comment]
![Screenshot from 2020-05-04 16-10-16](https://user-images.githubusercontent.com/42512858/80958874-5d632680-8e23-11ea-9ca5-98b2296331da.png)

I am getting this error

**Comment by jabbar86** [comment]
its looks like error is while starting the server.share the more details like package.json
